version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: test-task
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "${PORT}:${PORT}"

volumes:
  dbdata:
