// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group/{groupName}/species": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "Get the full list of fish species (with counts) currently detected inside the group.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Map of fish species with counts",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/group/{groupName}/species/top/{N}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "Get the list of top N fish species (with counts) currently detected inside the group.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of top fish species to retrieve",
                        "name": "N",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Map of top fish species with counts",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/group/{groupName}/temperature/average": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "Get the current average temperature inside the group.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Average temperature",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/group/{groupName}/transparency/average": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "group"
                ],
                "summary": "Get the current average transparency inside the group.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the group",
                        "name": "groupName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Average transparency",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/region/temperature/max": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "region"
                ],
                "summary": "Get the maximum temperature in the specified region.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Minimum x-coordinate of the region",
                        "name": "xMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Minimum y-coordinate of the region",
                        "name": "yMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Minimum z-coordinate of the region",
                        "name": "zMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum x-coordinate of the region",
                        "name": "xMax",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum y-coordinate of the region",
                        "name": "yMax",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum z-coordinate of the region",
                        "name": "zMax",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Maximum temperature in the region",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/region/temperature/min": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "region"
                ],
                "summary": "Get the minimum temperature in the specified region.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Minimum x-coordinate of the region",
                        "name": "xMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Minimum y-coordinate of the region",
                        "name": "yMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Minimum z-coordinate of the region",
                        "name": "zMin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum x-coordinate of the region",
                        "name": "xMax",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum y-coordinate of the region",
                        "name": "yMax",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum z-coordinate of the region",
                        "name": "zMax",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Minimum temperature in the region",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Halo Lab test task",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
